version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    allow:
      - dependency-name: "phpstan/phpstan"
      - dependency-name: "squizlabs/php_codesniffer"
      - dependency-name: "phpunit/phpunit"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/testing/playwright"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
