<?php
declare(strict_types=1);

/**
 * @module db
 *
 * DB-layer helpers extracted from lib.php in v3.30.0 (ADR-004 Phase 2
 * Task 4.1). Connection bootstrap (ipam_db), dialect selection, schema
 * self-heal (audit_log, schema_migrations), migration runner, and
 * SQLite dump tooling. Functions stay in the global namespace per
 * ADR-004 Option E.
 *
 * Inclusion rule: functions that operate on PDO connections, the schema,
 * or the migration runner.
 *
 * Dependencies: lib/utils.php (to_int, to_str), lib/config.php (ipam_config,
 * ipam_config_nested), the dialects/ class hierarchy (Dialect + Sqlite/
 * Mysql/Pgsql implementations), PgsqlStatement.php, and migrations.php.
 *
 * ADR-003 applied at extraction time: every former `global $config;` read
 * is replaced with an ipam_config('key') call. This is the first module to
 * apply the v3.30.0 accessor pattern at extraction.
 *
 * Invariant #2 (CLAUDE.md): apply_migrations() brackets every migration
 * with `PRAGMA foreign_keys = OFF` BEFORE `BEGIN`. The bracket logic was
 * moved byte-identically from lib.php — do not "improve" it. v2.2.1 wipe
 * is the originating incident.
 *
 * #911 (A16): bootstrap-admin INSERT in ipam_db_init() previously
 * duplicated across the fresh-schema and "users-table-empty self-heal"
 * branches. Collapsed into a single ipam_db_init_bootstrap_admin() helper.
 *
 * #921 (C8): ipam_table_exists(PDO, string): bool — fresh helper for
 * cross-engine table existence probes. Previously open-coded as closures
 * inside each migration callback in migrations.php; new code (and #1207
 * sweep) should call this instead.
 */

/**
 * Returns the active SQL dialect (#378). ipam_db() bootstraps this once per
 * request based on $config['db_driver'] and stows it under
 * $GLOBALS['ipam_dialect']. v2.9.0 shipped SqliteDialect only; v2.10.0 adds
 * MysqlDialect (#382); v2.11.0 adds PgsqlDialect (#386). Tests and CLI
 * scripts that bootstrap lib.php directly (without going through ipam_db())
 * get a SqliteDialect lazily — that is the historical default and matches
 * what every test fixture expects.
 */
function ipam_dialect(): Dialect
{
    if (!isset($GLOBALS['ipam_dialect']) || !($GLOBALS['ipam_dialect'] instanceof Dialect)) {
        require_once __DIR__ . '/../dialects/Dialect.php';
        require_once __DIR__ . '/../dialects/DialectValidator.php';
        require_once __DIR__ . '/../dialects/SqliteDialect.php';
        $GLOBALS['ipam_dialect'] = new SqliteDialect();
    }
    return $GLOBALS['ipam_dialect'];
}

/**
 * Select and cache the active dialect from a config array. Called by
 * ipam_db() during connection bootstrap; safe to call standalone from
 * tests that need to pin a specific dialect without opening a connection.
 *
 * @param array<string, mixed> $config
 */
function ipam_dialect_from_config(array $config): Dialect
{
    require_once __DIR__ . '/../dialects/Dialect.php';
    require_once __DIR__ . '/../dialects/DialectValidator.php';
    $driverRaw = $config['db_driver'] ?? 'sqlite';
    $driver = is_string($driverRaw) ? $driverRaw : 'sqlite';
    switch ($driver) {
        case 'mysql':
            require_once __DIR__ . '/../dialects/MysqlDialect.php';
            $dialect = new MysqlDialect();
            break;
        case 'pgsql':
            require_once __DIR__ . '/../dialects/PgsqlDialect.php';
            $dialect = new PgsqlDialect();
            break;
        case 'sqlite':
        case '':
            require_once __DIR__ . '/../dialects/SqliteDialect.php';
            $dialect = new SqliteDialect();
            break;
        default:
            throw new RuntimeException("Unsupported db_driver: $driver");
    }
    $GLOBALS['ipam_dialect'] = $dialect;
    return $dialect;
}

/**
 * Returns true when the active DB engine supports the SQL dump/restore
 * feature in db_tools.php (SQLite only). Used to conditionally show the
 * Database Tools nav item — direct navigation to db_tools.php still works
 * on all engines (it shows an "unsupported" banner).
 */
function ipam_sql_dump_supported(): bool {
    return ipam_dialect()->driver_name() === 'sqlite';
}

/**
 * Return the auto-generated ID from the last INSERT on $db.
 *
 * On SQLite and MySQL, PDO::lastInsertId() works without arguments. On
 * Postgres, pdo_pgsql requires the sequence name — without it,
 * lastInsertId() returns "0" because Postgres doesn't have a
 * connection-scoped "last insert id" concept; it tracks per-sequence.
 * `GENERATED BY DEFAULT AS IDENTITY` columns create an implicit
 * sequence named `<table>_<column>_seq`.
 *
 * Every INSERT call site must use this helper instead of calling
 * $db->lastInsertId() directly — the raw call is a silent data-
 * corruption bug on Postgres (returns 0, breaks audit entity_id,
 * redirect URLs, tag saving, and every cascading operation that
 * references the newly-inserted row). v2.11.0 #388.
 */
function ipam_last_insert_id(PDO $db, string $table, string $column = 'id'): int
{
    $driverRaw = $db->getAttribute(PDO::ATTR_DRIVER_NAME);
    $driver = is_string($driverRaw) ? $driverRaw : '';
    if ($driver === 'pgsql') {
        return (int)$db->lastInsertId("{$table}_{$column}_seq");
    }
    return (int)$db->lastInsertId();
}

/**
 * Return the settings.key column quoted for the active SQL dialect.
 *
 * `key` is a reserved word in MySQL (index keyword) and must be quoted.
 * MySQL uses backticks; Postgres and SQLite use double quotes (SQL
 * standard). There is no single quoting syntax that works on all three
 * engines without a SQL-mode change, so we branch on the driver. Called
 * by every settings query in lib.php and migrations.php. v2.11.0 #388.
 */
function ipam_key_col(): string
{
    return ipam_dialect()->driver_name() === 'mysql' ? '`key`' : '"key"';
}

/**
 * Cross-engine table existence probe. v3.30.0 #921 (C8).
 *
 * Previously open-coded as closures inside each migration callback in
 * migrations.php (and as `table_exists()` in migrate_db.php). This is the
 * canonical helper for new code; existing closures may be swept to this
 * helper under #1207.
 *
 * Per-driver SQL:
 *   sqlite — sqlite_master where type='table'
 *   mysql  — information_schema.tables (current schema)
 *   pgsql  — to_regclass()
 *
 * Returns false on any probe failure (caller falls through to whatever
 * CREATE TABLE IF NOT EXISTS path it intended).
 */
function ipam_table_exists(PDO $db, string $name): bool
{
    $driverRaw = $db->getAttribute(PDO::ATTR_DRIVER_NAME);
    $driver = is_string($driverRaw) ? $driverRaw : '';
    try {
        switch ($driver) {
            case 'sqlite':
                $st = $db->prepare(
                    "SELECT 1 FROM sqlite_master WHERE type='table' AND name = :n"
                );
                $st->execute([':n' => $name]);
                return $st->fetchColumn() !== false;
            case 'mysql':
                $st = $db->prepare(
                    "SELECT 1 FROM information_schema.tables "
                    . "WHERE table_schema = DATABASE() AND table_name = :n"
                );
                $st->execute([':n' => $name]);
                return $st->fetchColumn() !== false;
            case 'pgsql':
                $st = $db->prepare("SELECT to_regclass(:n) IS NOT NULL");
                $st->execute([':n' => $name]);
                $val = $st->fetchColumn();
                if (is_bool($val)) {
                    return $val;
                }
                return $val === 't' || $val === 1 || $val === '1';
            default:
                return false;
        }
    } catch (PDOException) {
        return false;
    }
}

/**
 * Open a PDO connection based on $config['db_driver'].
 *
 * Dispatcher for the multi-engine support introduced in v2.10.0. Picks the
 * dialect first (so ipam_dialect() returns the right instance for the rest
 * of the request), then connects to the selected engine.
 *
 * Supported drivers:
 *   - 'sqlite' (default) — uses $config['db_path'] as the file path.
 *   - 'mysql' (stable, v3.0.0) — uses $config['db_dsn'],
 *     $config['db_user'], $config['db_pass']. Requires MySQL 8.0.29+.
 *   - 'pgsql' (stable, v3.0.0) — uses $config['db_dsn'],
 *     $config['db_user'], $config['db_pass']. Requires PostgreSQL 14+.
 *
 * @param array<string, mixed> $config
 */
function ipam_db(array $config): PDO
{
    $dialect = ipam_dialect_from_config($config);

    switch ($dialect->driver_name()) {
        case 'sqlite':
            $pathRaw = $config['db_path'] ?? '';
            $path = is_string($pathRaw) ? $pathRaw : '';
            if ($path === '') {
                throw new RuntimeException('ipam_db: sqlite driver requires $config[\'db_path\']');
            }
            $dir = dirname($path);
            if (!is_dir($dir)) {
                mkdir($dir, 0700, true);
            }
            $pdo = new PDO('sqlite:' . $path, null, null, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);
            $pdo->exec("PRAGMA journal_mode = WAL;");
            $pdo->exec("PRAGMA busy_timeout = 30000;");
            break;

        case 'mysql':
            $dsnRaw  = $config['db_dsn']  ?? '';
            $userRaw = $config['db_user'] ?? '';
            $passRaw = $config['db_pass'] ?? '';
            $dsn  = is_string($dsnRaw)  ? $dsnRaw  : '';
            $user = is_string($userRaw) ? $userRaw : '';
            $pass = is_string($passRaw) ? $passRaw : '';
            if ($dsn === '') {
                throw new RuntimeException('ipam_db: mysql driver requires $config[\'db_dsn\']');
            }
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);
            // 8.0.29 is the effective minimum. ensure_audit_log_table()
            // and MysqlDialect::append_only_trigger() both emit
            // `CREATE TRIGGER IF NOT EXISTS`, a syntax feature added in
            // MySQL 8.0.29. Earlier 8.0.x servers pass a naive `8.0.0`
            // check and then crash on the first self-heal bootstrap.
            // Reject at connect time so failures are clear and immediate.
            $serverVersionRaw = $pdo->getAttribute(PDO::ATTR_SERVER_VERSION);
            $serverVersion = is_string($serverVersionRaw) ? $serverVersionRaw : '';

            // v2.12.0 #534: first-class MariaDB 10.11+ support.
            // PDO::ATTR_SERVER_VERSION returns e.g. "10.11.6-MariaDB" or
            // "5.5.5-10.11.6-MariaDB" (the 5.5.5 prefix is a historical
            // protocol-compat lie). Detect MariaDB, strip the prefix, and
            // enforce a separate version floor.
            if ($serverVersion !== '' && stripos($serverVersion, 'mariadb') !== false) {
                $cleaned = preg_replace('/^5\.5\.5-/', '', $serverVersion);
                $cleaned = is_string($cleaned) ? $cleaned : $serverVersion;
                preg_match('/^(\d+\.\d+\.\d+)/', $cleaned, $mariaMatch);
                $mariaVersion = $mariaMatch[1] ?? '0.0.0';
                if (version_compare($mariaVersion, '10.11.0', '<')) {
                    throw new RuntimeException(
                        "MariaDB 10.11.0+ is required (server reports '$serverVersion')"
                    );
                }
                break;
            }

            if ($serverVersion === '' || version_compare($serverVersion, '8.0.29', '<')) {
                throw new RuntimeException(
                    "MySQL 8.0.29+ is required (server reports '$serverVersion')"
                );
            }
            break;

        case 'pgsql':
            // v2.11.0 #386 experimental Postgres driver. Uses the same
            // $config['db_dsn'] / $config['db_user'] / $config['db_pass']
            // keys as the MySQL branch so config.php shape is symmetric.
            $dsnRaw  = $config['db_dsn']  ?? '';
            $userRaw = $config['db_user'] ?? '';
            $passRaw = $config['db_pass'] ?? '';
            $dsn  = is_string($dsnRaw)  ? $dsnRaw  : '';
            $user = is_string($userRaw) ? $userRaw : '';
            $pass = is_string($passRaw) ? $passRaw : '';
            if ($dsn === '') {
                throw new RuntimeException('ipam_db: pgsql driver requires $config[\'db_dsn\']');
            }
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ]);
            // 14 is the effective minimum. PgsqlDialect::append_only_trigger()
            // emits `CREATE OR REPLACE TRIGGER`, a syntax feature added in
            // PG14. Earlier Postgres servers would fail on the first
            // ensure_audit_log_table() self-heal. Reject at connect time so
            // failures are clear and immediate.
            //
            // PDO::ATTR_SERVER_VERSION on pdo_pgsql returns a bare numeric
            // string like "14.10" or "17.2" (no "-MariaDB"-style suffix
            // concerns). version_compare handles these cleanly.
            $serverVersionRaw = $pdo->getAttribute(PDO::ATTR_SERVER_VERSION);
            $serverVersion = is_string($serverVersionRaw) ? $serverVersionRaw : '';
            if ($serverVersion === '' || version_compare($serverVersion, '14.0', '<')) {
                throw new RuntimeException(
                    "PostgreSQL 14+ is required (server reports '$serverVersion'). "
                    . 'For v2.11.0, use Postgres 14+ or stay on the SQLite driver.'
                );
            }
            // Force client_encoding to UTF-8 so binary IP round-trips and
            // text comparisons are deterministic regardless of the server's
            // default. Matches the implicit UTF-8 assumption on SQLite and
            // MySQL (utf8mb4).
            $pdo->exec("SET client_encoding = 'UTF8'");
            // pdo_pgsql returns BYTEA columns as PHP stream resources rather
            // than strings, regardless of how they were bound. Without an
            // auto-unwrap, every `ip_bin` / `network_bin` SELECT in the
            // codebase would break on pgsql. Install a custom PDOStatement
            // subclass that walks each fetched row and stream_get_contents()
            // any resource values. This keeps the ~80 existing call sites
            // unchanged. Surfaced by PgsqlSmokeTest during v2.11.0 #387.
            require_once __DIR__ . '/../PgsqlStatement.php';
            $pdo->setAttribute(PDO::ATTR_STATEMENT_CLASS, [PgsqlStatement::class]);
            break;

        default:
            throw new RuntimeException('ipam_db: unreachable — unsupported driver ' . $dialect->driver_name());
    }

    $fk = $dialect->pragma_foreign_keys(true);
    if ($fk !== null) {
        $pdo->exec($fk);
    }
    return $pdo;
}

/**
 * Create the audit_log table and its append-only triggers (idempotent).
 * Centralises DDL that was previously duplicated in 4 places.
 *
 * Routes type declarations and triggers through the active dialect so
 * fresh MySQL / Postgres installs emit engine-valid DDL. On SQLite the
 * resulting text matches the pre-v2.10.0 literals byte-for-byte. Per
 * the v2.10.0 schema-files decision: historical migration closures are
 * NOT refactored — schema.mysql.sql / schema.pgsql.sql pre-populate
 * schema_migrations so replay is a no-op on fresh non-SQLite installs.
 */
function ensure_audit_log_table(PDO $db): void
{
    // Probe first: if audit_log already exists, skip the full CREATE
    // TABLE / CREATE INDEX / CREATE TRIGGER path on this request. The
    // probe is a no-row SELECT — a few microseconds per page on every
    // engine.
    //
    // Without this short-circuit, ipam_db_init() runs the full CREATE
    // path on every page load. On Postgres the CREATE OR REPLACE TRIGGER
    // emitted by PgsqlDialect::append_only_trigger() races on the system
    // catalog when multiple concurrent requests (page + sub-resource
    // assets, or parallel API calls) hit init.php at the same time —
    // surfacing as SQLSTATE[XX000] "tuple concurrently updated" and a
    // sporadic 500 on whichever request lost the race. Documented in the
    // v3.24.0 release notes.
    //
    // No process-wide caching: demo_reset_db() drops audit_log mid-
    // request, so a cache that persists across calls would skip the
    // self-heal that the next request needs. The probe is cheap enough
    // to run every time. The race protection comes from the probe
    // gating the CREATE OR REPLACE — if the table exists, no DDL fires.
    try {
        $probe = $db->query("SELECT 1 FROM audit_log LIMIT 0");
        if ($probe !== false) {
            $probe->closeCursor();
            // Table exists. Verify the append-only triggers also exist;
            // if either is missing (operator manually dropped them, an
            // external migration omitted them, etc.) we MUST recreate
            // them so audit-row immutability stays enforced. The probe
            // is one extra cheap row-count query per request — much
            // smaller than rebuilding the table + indexes — and it
            // preserves the v3.24.0 race fix because the CREATE OR
            // REPLACE TRIGGER path only runs when triggers are
            // genuinely missing (rare; never on the steady-state
            // request path).
            if (!ipam_audit_log_triggers_present($db)) {
                ensure_audit_log_triggers($db);
            }
            return;
        }
    } catch (PDOException) {
        // table missing — fall through to the full create + trigger path
    }

    $d = ipam_dialect();
    // action and created_at are indexed below, so they must use the
    // indexed text type (VARCHAR on MySQL, TEXT elsewhere). Free-form
    // unindexed columns (username, entity_type, ip, user_agent, details)
    // stay as plain TEXT.
    $idxText = $d->indexed_text_type();
    $db->exec("
        CREATE TABLE IF NOT EXISTS audit_log (
          id          " . $d->autoincrement() . ",
          created_at  $idxText NOT NULL DEFAULT (" . $d->now() . "),
          user_id     INTEGER, username TEXT, action $idxText NOT NULL,
          entity_type TEXT NOT NULL, entity_id INTEGER,
          ip TEXT, user_agent TEXT, details TEXT
        )
    ");
    // CREATE INDEX IF NOT EXISTS is a SQLite idiom. MySQL 8.0.0–8.0.28 do
    // not accept it (IF NOT EXISTS on CREATE INDEX landed in 8.0.29, which
    // is above our effective 8.0.29 floor), so we use a helper that swallows
    // the MySQL "Duplicate key name" error (errno 1061). On SQLite the
    // IF NOT EXISTS is native and the catch never fires.
    $createIndex = static function (PDO $db, string $name, string $table, string $col): void {
        try {
            $db->exec("CREATE INDEX IF NOT EXISTS $name ON $table($col)");
        } catch (PDOException $e) {
            $msg = $e->getMessage();
            // MySQL raises 1061 with "Duplicate key name" when the index
            // already exists. On MySQL 8.0.0–8.0.28, CREATE INDEX IF NOT
            // EXISTS itself is rejected (syntax error 1064) — retry with
            // plain CREATE INDEX, then swallow 1061 if the index is
            // already there.
            $sqlstate = (string)($e->errorInfo[0] ?? '');
            if ($sqlstate === '42000' && stripos($msg, 'syntax') !== false) {
                try {
                    $db->exec("CREATE INDEX $name ON $table($col)");
                } catch (PDOException $e2) {
                    if (stripos($e2->getMessage(), 'duplicate key name') === false) {
                        throw $e2;
                    }
                }
                return;
            }
            throw $e;
        }
    };
    $createIndex($db, 'idx_audit_log_action',     'audit_log', 'action');
    $createIndex($db, 'idx_audit_log_created_at', 'audit_log', 'created_at');
    ensure_audit_log_triggers($db);
}

/**
 * (Re)create the audit_log append-only triggers (idempotent).
 *
 * Extracted from ensure_audit_log_table() so callers that explicitly
 * DROP the triggers — currently only prune_audit_log() under SQLite —
 * can put them back without relying on a side effect of the table-
 * creation function. ensure_audit_log_table()'s probe returns early
 * when the table exists, so it cannot be the recovery path for missing
 * triggers in isolation.
 */
function ensure_audit_log_triggers(PDO $db): void
{
    $d = ipam_dialect();
    foreach ($d->append_only_trigger('audit_log') as $stmt) {
        try {
            $db->exec($stmt);
        } catch (PDOException $e) {
            // MySQL 8.0.0–8.0.28 do not support CREATE TRIGGER IF NOT EXISTS
            // (added in 8.0.29). Swallow "Trigger already exists" (errno 1359)
            // so the self-heal path is idempotent on every supported 8.0.x.
            if (stripos($e->getMessage(), 'already exists') === false) {
                throw $e;
            }
        }
    }
}

/**
 * Probe for the audit_log append-only triggers. Returns true iff BOTH
 * audit_log_no_update and audit_log_no_delete exist on this driver.
 *
 * Used by ensure_audit_log_table() to keep the steady-state fast path
 * cheap (one SELECT per request) while still self-healing if an external
 * action drops the triggers — preserving the v3.24.0 race fix because
 * CREATE OR REPLACE TRIGGER only fires when the probe says they're
 * missing, never on the steady-state path.
 *
 * Per-driver SQL:
 *   sqlite — sqlite_master where type='trigger'
 *   mysql  — information_schema.triggers (current schema)
 *   pgsql  — pg_trigger ⨝ pg_class on tgrelid
 *
 * Returns false on any probe failure so the caller falls through to
 * ensure_audit_log_triggers() (idempotent on every engine).
 */
function ipam_audit_log_triggers_present(PDO $db): bool
{
    // Dialect::driver_name() is constrained to 'sqlite' | 'mysql' |
    // 'pgsql' by the type system, so the match is exhaustive. If a
    // future driver is added, PHP will surface UnhandledMatchError
    // until the new arm lands here — exactly the safety we want.
    $sql = match (ipam_dialect()->driver_name()) {
        'sqlite' =>
            "SELECT COUNT(*) FROM sqlite_master " .
            "WHERE type = 'trigger' " .
            "AND name IN ('audit_log_no_update', 'audit_log_no_delete')",
        'mysql' =>
            "SELECT COUNT(*) FROM information_schema.triggers " .
            "WHERE event_object_table = 'audit_log' " .
            "AND trigger_name IN ('audit_log_no_update', 'audit_log_no_delete') " .
            "AND trigger_schema = DATABASE()",
        'pgsql' =>
            "SELECT COUNT(*) FROM pg_trigger t " .
            "JOIN pg_class c ON c.oid = t.tgrelid " .
            "WHERE c.relname = 'audit_log' " .
            "AND t.tgname IN ('audit_log_no_update', 'audit_log_no_delete')",
    };
    try {
        $st = $db->query($sql);
        if ($st === false) {
            return false;
        }
        return to_int($st->fetchColumn()) >= 2;
    } catch (PDOException) {
        return false;
    }
}

/**
 * Insert the bootstrap admin user (v3.30.0 #911 / A16 dedupe).
 *
 * Previously inlined twice in ipam_db_init() — once in the fresh-schema
 * branch, once in the "users-table-empty self-heal" branch. The two
 * copies were byte-identical except for surrounding context; they have
 * been collapsed into this single helper so a future credential-policy
 * change (password rules, role expansion, MFA seeding) happens in one
 * place. Reads bootstrap_admin.username / bootstrap_admin.password via
 * ipam_config_nested() (ADR-003).
 *
 * Idempotency is the caller's responsibility — ipam_db_init() only calls
 * this when (a) the schema was just created from scratch or (b) the
 * users table is empty. Calling it on a populated users table will fail
 * the UNIQUE(username) constraint, which is the correct behaviour.
 */
function ipam_db_init_bootstrap_admin(PDO $db): void
{
    $u = ipam_config_nested('bootstrap_admin', 'username');
    $p = ipam_config_nested('bootstrap_admin', 'password');
    $hash = password_hash(to_str($p), PASSWORD_DEFAULT);
    $ins = $db->prepare("INSERT INTO users (username, password_hash, role, is_active) VALUES (:u,:h,'admin',1)");
    $ins->execute([':u' => to_str($u), ':h' => $hash]);
}

function ipam_db_init(PDO $db): void
{
    $driver = ipam_dialect()->driver_name();

    // Probe for the users table on THIS handle. A lightweight SELECT with a
    // caught "table not found" — works on every engine without needing
    // sqlite_master / information_schema branching.
    $hasUsers = false;
    try {
        $probe = $db->query("SELECT 1 FROM users LIMIT 1");
        if ($probe !== false) {
            $probe->closeCursor();
            $hasUsers = true;
        }
    } catch (PDOException) {
        $hasUsers = false;
    }

    // SQLite-only fast path: when the handle already has the schema AND the
    // sentinel file is at least as new as the SQLite DB file, skip the
    // per-bootstrap probe/migration churn. MySQL has no local file to stat,
    // so this optimisation does not apply there.
    //
    // The $hasUsers guard is load-bearing: it keeps a sqlite::memory: handle
    // (which does NOT correspond to the on-disk db_path the sentinel stats —
    // e.g. unit tests that call ipam_db_init() directly) from wrongly taking
    // the fast path and running apply_migrations() against an empty in-memory
    // database. Migrations assume the schema.sql baseline already exists, so
    // a fresh handle MUST fall through to the schema-creation branch below.
    // (#1175 — RestoreDryRunTest::testIpambkl1ArchiveDoesNotErrorThroughSqlSplitter.)
    if ($driver === 'sqlite' && $hasUsers) {
        // Honour a deployment's configured db_path so the sentinel check
        // stats the real database file, not the default one. The sentinel
        // itself lives next to the DB file so custom paths stay
        // self-contained.
        $dbPathRaw  = ipam_config('db_path');
        $dbFilePath = is_string($dbPathRaw) && $dbPathRaw !== ''
            ? $dbPathRaw
            : __DIR__ . '/../data/ipam.sqlite';
        $sentinelPath = dirname($dbFilePath) . '/.db_initialized';
        if (is_file($sentinelPath) && is_file($dbFilePath)) {
            $sentinelTime = (int)filemtime($sentinelPath);
            $dbTime       = (int)filemtime($dbFilePath);
            if ($sentinelTime >= $dbTime) {
                ensure_migrations_table($db);
                apply_migrations($db);
                ensure_audit_log_table($db); // self-heal if table was dropped
                return;
            }
        }
    }

    if (!$hasUsers) {
        $schemaFile = __DIR__ . '/../schema.sql';
        if ($driver === 'mysql') {
            $schemaFile = __DIR__ . '/../schema.mysql.sql';
        } elseif ($driver === 'pgsql') {
            $schemaFile = __DIR__ . '/../schema.pgsql.sql';
        }
        $schema = file_get_contents($schemaFile);
        if ($schema === false) throw new RuntimeException("Cannot read " . basename($schemaFile));
        $db->exec($schema);

        // #911 (A16): single bootstrap-admin INSERT helper; previously
        // duplicated between the fresh-schema and self-heal branches.
        ipam_db_init_bootstrap_admin($db);

        // Stamp all known migrations as already satisfied by the fresh schema.
        // schema.mysql.sql already pre-seeds these rows so the INSERT below
        // is a no-op on MySQL — upsert_or_ignore() makes that explicit and
        // lets the same path work on every driver.
        ensure_migrations_table($db);
        require_once __DIR__ . '/../migrations.php';
        $ignore = ipam_dialect()->upsert_or_ignore('schema_migrations', ['version']);
        $stamp = $db->prepare("INSERT INTO schema_migrations (version) VALUES (:v) $ignore");
        foreach (array_keys(ipam_migrations()) as $ver) {
            $stamp->execute([':v' => $ver]);
        }
        return;
    }

    ensure_migrations_table($db);
    apply_migrations($db);

    // Self-healing: audit_log is created by schema.sql, not a migration, so it can
    // go missing after a botched demo reset. Recreate it (and its triggers) if absent.
    ensure_audit_log_table($db);

    $st = $db->prepare("SELECT COUNT(*) AS c FROM users");
    $st->execute();
    /** @var array<string, mixed>|false $countRow */
    $countRow = $st->fetch();
    $count = is_array($countRow) ? to_int($countRow['c']) : 0;
    if ($count === 0) {
        // #911 (A16): single bootstrap-admin INSERT helper.
        ipam_db_init_bootstrap_admin($db);
    }

    // Write sentinel so subsequent requests skip bootstrap queries (SQLite
    // only — the sentinel is a filesystem optimisation for the local DB
    // file and has no meaning on MySQL). Location must match the path
    // derived in the fast-path above: next to the resolved db_path file.
    if ($driver === 'sqlite') {
        $dbPathRaw  = ipam_config('db_path');
        $dbFilePath = is_string($dbPathRaw) && $dbPathRaw !== ''
            ? $dbPathRaw
            : __DIR__ . '/../data/ipam.sqlite';
        @touch(dirname($dbFilePath) . '/.db_initialized');
    }
}

function ensure_migrations_table(PDO $db): void
{
    $d = ipam_dialect();
    // version has a UNIQUE constraint so it must use the indexed text type
    // (VARCHAR on MySQL, TEXT elsewhere).
    $db->exec("CREATE TABLE IF NOT EXISTS schema_migrations (
        id " . $d->autoincrement() . ",
        version " . $d->indexed_text_type() . " NOT NULL UNIQUE,
        applied_at TEXT NOT NULL DEFAULT (" . $d->now() . ")
    )");
}

/** @return list<string> */
function applied_migrations(PDO $db): array
{
    $st = $db->prepare("SELECT version FROM schema_migrations");
    $st->execute();
    /** @var list<array<string, mixed>> $rows */
    $rows = $st->fetchAll();
    return array_map(fn(array $r): string => to_str($r['version']), $rows);
}

/** @return list<string> */
function apply_migrations(PDO $db): array
{
    ensure_migrations_table($db);
    require_once __DIR__ . '/../migrations.php';

    $migs = ipam_migrations();
    ksort($migs, SORT_NATURAL);

    $done = array_flip(applied_migrations($db));
    $appliedNow = [];

    foreach ($migs as $ver => $fn) {
        if (isset($done[$ver])) continue;

        // SQLite DDL (DROP TABLE, ALTER TABLE) needs a full exclusive lock —
        // even readers block it. busy_timeout only retries SQLITE_BUSY (5),
        // not SQLITE_LOCKED (6), so we retry at the PHP level: ROLLBACK the
        // transaction, sleep 1 s, and try again. SQLite DDL is fully
        // transactional so ROLLBACK cleanly undoes any partial work.
        $lastErr  = null;
        $applied  = false;
        // Route FK toggling through the dialect so non-SQLite engines (MySQL
        // via SET FOREIGN_KEY_CHECKS, Postgres via null / deferred constraints)
        // get the engine-appropriate statement. Null means the engine has no
        // per-connection FK toggle and we rely on other mechanisms instead.
        $dialect = ipam_dialect();
        $fkOff   = $dialect->pragma_foreign_keys(false);
        $fkOn    = $dialect->pragma_foreign_keys(true);
        $toggleFk = static function (PDO $db, ?string $stmt): void {
            if ($stmt !== null) {
                $db->exec($stmt);
            }
        };
        for ($attempt = 0; $attempt < 60 && !$applied; $attempt++) {
            if ($attempt > 0) {
                sleep(1);
            }

            // FK enforcement must be toggled outside the transaction. On
            // SQLite, PRAGMA foreign_keys cannot be changed inside BEGIN; and
            // with FK ON, DROP TABLE triggers an implicit row-by-row DELETE
            // that cascades ON DELETE CASCADE children (addresses,
            // subnet_tags, etc.), wiping all data. Disabling around each
            // migration prevents the cascade. FK enforcement is restored
            // unconditionally in every exit path.
            $toggleFk($db, $fkOff);

            try {
                // SQLite's `BEGIN EXCLUSIVE` acquires a table-level write
                // lock up front, which is required around DDL to avoid
                // SQLITE_LOCKED mid-migration. MySQL / Postgres don't need
                // (and don't accept) the EXCLUSIVE modifier — their DDL
                // acquires its own metadata locks. Fall back to a plain
                // transaction on non-SQLite engines.
                if ($dialect->driver_name() === 'sqlite') {
                    $db->exec("BEGIN EXCLUSIVE");
                } else {
                    $db->exec("START TRANSACTION");
                }
            } catch (Throwable $e) {
                $toggleFk($db, $fkOn);
                $lastErr = $e;
                if (stripos($e->getMessage(), 'locked') !== false || stripos($e->getMessage(), 'busy') !== false) {
                    continue;
                }
                throw $e;
            }

            try {
                $fn($db);
                $st = $db->prepare("INSERT INTO schema_migrations (version) VALUES (:v)");
                $st->execute([':v' => $ver]);
                $db->exec("COMMIT");
                $applied = true;
                $appliedNow[] = $ver;
                $lastErr = null;
            } catch (Throwable $e) {
                try { $db->exec("ROLLBACK"); } catch (Throwable) {}
                $toggleFk($db, $fkOn);
                $lastErr = $e;
                if (stripos($e->getMessage(), 'locked') !== false || stripos($e->getMessage(), 'busy') !== false) {
                    continue;
                }
                throw $e;
            }
            $toggleFk($db, $fkOn);
        }

        if ($lastErr !== null) {
            throw $lastErr;
        }
    }

    return $appliedNow;
}

/**
 * v3.29.0 #1102 — count of registered migrations. Tests auto-derive
 * instead of hardcoding a literal that drifts every release.
 */
function ipam_migrations_count(): int
{
    require_once __DIR__ . '/../migrations.php';
    return count(ipam_migrations());
}

/**
 * Stream an SQLite database dump to a write callback. SQLite-only.
 *
 * Caller supplies a `callable(string $chunk): void` that receives the
 * dump piece by piece — keeps memory flat on large DBs. The companion
 * ipam_db_dump() collects the output into a single string for callers
 * that need the whole dump in memory.
 */
function ipam_db_dump_stream(PDO $db, callable $write): void
{
    // SQLite-format dump only. Every query in this function depends on
    // sqlite_master and SQLite-specific PRAGMA output. Cross-engine
    // dump/restore lands in v3.0.0 via migrate_db.php (#392). db_tools.php
    // gates the entry point on driver; this is defence-in-depth for any
    // direct caller that slips past it.
    if (ipam_dialect()->driver_name() !== 'sqlite') {
        throw new \RuntimeException(
            'ipam_db_dump_stream() is SQLite-only. Use engine-native tooling '
            . '(mysqldump / pg_dump) on other drivers until v3.0.0 migrate_db.php.'
        );
    }

    $write("-- Simple PHP IPAM database dump\n");
    $write("-- Generated: " . date('Y-m-d H:i:s') . "\n\n");
    $write("PRAGMA foreign_keys=OFF;\n");
    $write("BEGIN TRANSACTION;\n\n");

    // Tables: schema + data
    $tables = ($db->query(
        "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ) ?: throw new \RuntimeException('Query failed'))->fetchAll();

    foreach ($tables as $t) {
        $name        = to_str($t['name']);
        $quotedName  = '"' . str_replace('"', '""', $name) . '"';
        $write("-- Table: {$name}\n");
        $write(to_str($t['sql']) . ";\n");

        // Dump triggers for this table so they are recreated on import.
        $triggers = ($db->query(
            "SELECT sql FROM sqlite_master WHERE type='trigger' AND tbl_name="
            . $db->quote($name) . " AND sql IS NOT NULL ORDER BY name"
        ) ?: throw new \RuntimeException('Query failed'))->fetchAll();
        foreach ($triggers as $trig) {
            $write(to_str($trig['sql']) . ";\n");
        }

        // Identify BLOB columns so we can always hex-encode raw binary data.
        $colInfo  = ($db->query("PRAGMA table_info({$quotedName})")
            ?: throw new \RuntimeException('Query failed'))->fetchAll();
        $blobCols = [];
        foreach ($colInfo as $ci) {
            if (strtoupper(to_str($ci['type'])) === 'BLOB') {
                $blobCols[to_str($ci['name'])] = true;
            }
        }

        $rows = ($db->query("SELECT * FROM {$quotedName}")
            ?: throw new \RuntimeException('Query failed'))->fetchAll();
        foreach ($rows as $row) {
            $cols = array_map(
                fn($c) => '"' . str_replace('"', '""', (string)$c) . '"',
                array_keys($row)
            );
            $vals = [];
            foreach ($row as $colName => $v) {
                if ($v === null) {
                    $vals[] = 'NULL';
                } elseif (is_int($v) || is_float($v)) {
                    $vals[] = (string)$v;
                } elseif (isset($blobCols[$colName])) {
                    $vals[] = "X'" . bin2hex(to_str($v)) . "'";
                } else {
                    $vals[] = "CAST(X'" . bin2hex(to_str($v)) . "' AS TEXT)";
                }
            }
            $write("INSERT INTO {$quotedName} (" . implode(',', $cols) . ") VALUES ("
                  . implode(',', $vals) . ");\n");
        }
        $write("\n");
    }

    // Indices (non-system)
    $indices = ($db->query(
        "SELECT sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ) ?: throw new \RuntimeException('Query failed'))->fetchAll();
    if ($indices) {
        $write("-- Indexes\n");
        foreach ($indices as $idx) {
            $write(to_str($idx['sql']) . ";\n");
        }
        $write("\n");
    }

    $write("COMMIT;\n");
    $write("PRAGMA foreign_keys=ON;\n");
}

/**
 * Generate a full SQL dump of the SQLite database suitable for import.
 * Backwards-compatible wrapper around ipam_db_dump_stream().
 */
function ipam_db_dump(PDO $db): string
{
    $out = '';
    ipam_db_dump_stream($db, function(string $chunk) use (&$out) {
        $out .= $chunk;
    });
    return $out;
}
