-- schema.pgsql.sql (v2.11.0 #387)
--
-- PostgreSQL 14+ authoritative schema for fresh installs. Equivalent to the
-- fully-migrated state of schema.sql (SQLite) + schema.mysql.sql through
-- v2.10.0. Migration replay on top of this file is a no-op because
-- schema_migrations is pre-populated with every historical version row at
-- the bottom of this script, matching schema.mysql.sql.
--
-- Conventions:
--   - BIGINT GENERATED BY DEFAULT AS IDENTITY for surrogate PKs (PG10+).
--     Chosen over BIGSERIAL because IDENTITY columns don't leave orphan
--     sequences on table drop and integrate cleanly with pg_dump.
--   - BYTEA for ip_bin / network_bin, native length (4 bytes for IPv4,
--     16 bytes for IPv6, never left-padded). Locked in #410.
--   - TIMESTAMP columns default to (NOW() AT TIME ZONE 'utc') so stored
--     values are UTC regardless of session timezone, matching SQLite's
--     datetime('now') and MySQL's UTC_TIMESTAMP().
--   - Byte-comparable text columns (usernames, CIDRs, IPs, hostnames,
--     hashes, settings keys) use COLLATE "C" so exact-equality,
--     uniqueness, and ordering stay deterministic regardless of the
--     cluster's LC_COLLATE. Matches MySQL's utf8mb4_bin and SQLite's
--     default BINARY collation.
--   - Append-only tables (audit_log) enforced via PL/pgSQL function +
--     BEFORE UPDATE/DELETE triggers raising an exception. Bypass for
--     housekeeping routines is via the custom GUC ipam.bypass_append_only
--     set with SET LOCAL. Matches PgsqlDialect::append_only_trigger()
--     byte-for-byte semantically.
--   - updated_at maintenance uses a single shared set_updated_at_utc()
--     PL/pgSQL function attached via per-table BEFORE UPDATE triggers.
--     CREATE OR REPLACE TRIGGER (PG14+) makes the bootstrap idempotent
--     without a drop-and-recreate race window.
--   - CHECK constraints honoured natively on all supported versions.
--   - oidc_sub uniqueness: Postgres UNIQUE treats NULLs as distinct
--     (SQL standard) so a plain UNIQUE column allows multiple NULLs
--     without the partial-index trick SQLite uses.
--
-- Minimum version: PostgreSQL 14. CREATE OR REPLACE TRIGGER is the
-- hard lower bound; ipam_db() also rejects earlier versions at connect.

-- ---------------------------------------------------------------------------
-- Shared PL/pgSQL helper: updated_at timestamp maintenance
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at_utc() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := (NOW() AT TIME ZONE 'utc');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username            TEXT COLLATE "C" NOT NULL UNIQUE,
  password_hash       TEXT NOT NULL,
  role                TEXT NOT NULL DEFAULT 'admin',
  is_active           SMALLINT NOT NULL DEFAULT 1,
  name                TEXT NOT NULL DEFAULT '',
  email               TEXT NOT NULL DEFAULT '',
  oidc_sub            TEXT COLLATE "C" NULL UNIQUE,
  last_login_at       TIMESTAMP NULL,
  password_changed_at TIMESTAMP NULL,
  theme               TEXT NOT NULL DEFAULT 'auto',
  timezone                 TEXT,
  pending_email            TEXT NULL,
  pending_email_token_hash TEXT COLLATE "C" NULL,
  pending_email_expires_at TIMESTAMP NULL,
  totp_secret_enc            TEXT,
  totp_enabled               SMALLINT NOT NULL DEFAULT 0,
  failed_auth_count          INTEGER NOT NULL DEFAULT 0,
  locked_until               TIMESTAMP WITH TIME ZONE,
  lock_reason                TEXT,
  email_otp_enabled            SMALLINT NOT NULL DEFAULT 0,
  email_otp_hash               TEXT,
  email_otp_expires_at         TIMESTAMP NULL,
  email_otp_attempts           INTEGER NOT NULL DEFAULT 0,
  preferred_mfa_method         TEXT NULL,
  created_at          TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at          TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
  -- No CHECK on role or theme: schema.sql (SQLite) has none, and
  -- demo_seed_data() inserts a display-only 'netops' user. Enum
  -- enforcement lives at the application layer.
);

CREATE OR REPLACE TRIGGER users_updated_at
  BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- sites (hierarchy supported via parent_id self-FK)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sites (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT COLLATE "C" NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  parent_id   BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_sites_parent_id ON sites(parent_id);

-- ---------------------------------------------------------------------------
-- vrfs (Virtual Routing and Forwarding)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vrfs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT COLLATE "C" NOT NULL UNIQUE,
  description    TEXT NOT NULL DEFAULT '',
  rd             TEXT NOT NULL DEFAULT '',
  asn            TEXT NOT NULL DEFAULT '',
  rt_import      TEXT NOT NULL DEFAULT '',
  rt_export      TEXT NOT NULL DEFAULT '',
  enforce_unique SMALLINT NOT NULL DEFAULT 1,
  created_at     TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at     TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_vrfs_name ON vrfs(name);

CREATE OR REPLACE TRIGGER vrfs_updated_at
  BEFORE UPDATE ON vrfs FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- vlans (first-class 802.1Q VLAN objects)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vlans (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vlan_id     INTEGER NOT NULL,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  site_id     BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_vlans_vlan_id_site_id UNIQUE (vlan_id, site_id),
  CONSTRAINT vlans_vlan_id_range CHECK (vlan_id BETWEEN 1 AND 4094)
);

CREATE OR REPLACE TRIGGER vlans_updated_at
  BEFORE UPDATE ON vlans FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- vlan_ranges (v2.4.0)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vlan_ranges (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  vlan_min    INTEGER NOT NULL,
  vlan_max    INTEGER NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  site_id     BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT vlan_ranges_min_range CHECK (vlan_min BETWEEN 1 AND 4094),
  CONSTRAINT vlan_ranges_max_range CHECK (vlan_max BETWEEN 1 AND 4094),
  CONSTRAINT vlan_ranges_order     CHECK (vlan_min <= vlan_max)
);

CREATE OR REPLACE TRIGGER vlan_ranges_updated_at
  BEFORE UPDATE ON vlan_ranges FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- subnets
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subnets (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidr        TEXT COLLATE "C" NOT NULL,
  ip_version  SMALLINT NOT NULL,
  network     TEXT COLLATE "C" NOT NULL,
  network_bin BYTEA NOT NULL,
  prefix      SMALLINT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  notes       TEXT NOT NULL DEFAULT '',
  site_id     BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  vlan_id     INTEGER NULL,
  vlan_fk     BIGINT NULL REFERENCES vlans(id) ON DELETE SET NULL,
  vrf_id          BIGINT NULL REFERENCES vrfs(id)  ON DELETE RESTRICT,
  alerts_enabled  SMALLINT NOT NULL DEFAULT 1,
  dhcp_routers     TEXT,                                             -- v3.4.0 #402: comma-sep gateway IPs
  dhcp_dns_servers TEXT,                                             -- v3.4.0 #402: comma-sep DNS IPs
  dhcp_domain_name TEXT,                                             -- v3.4.0 #402: domain name
  dhcp_lease_default INTEGER,                                        -- v3.4.0 #402: seconds (default-lease-time)
  dhcp_lease_max   INTEGER,                                          -- v3.4.0 #402: seconds (max-lease-time)
  dhcp_next_server TEXT,                                             -- v3.4.0 #402: TFTP server IP (PXE)
  dhcp_boot_filename TEXT,                                           -- v3.4.0 #402: boot filename (PXE)
  custom_fields TEXT NOT NULL DEFAULT '{}',                          -- v3.5.0 #313/#595: JSON key/value per-entity metadata
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_subnets_cidr_vrf UNIQUE (cidr, vrf_id)
);

CREATE INDEX IF NOT EXISTS idx_subnets_ver_prefix_netbin ON subnets(ip_version, prefix, network_bin);
CREATE INDEX IF NOT EXISTS idx_subnets_site_id ON subnets(site_id);
CREATE INDEX IF NOT EXISTS idx_subnets_vrf_id  ON subnets(vrf_id);
CREATE INDEX IF NOT EXISTS idx_subnets_vlan_fk ON subnets(vlan_fk);

CREATE OR REPLACE TRIGGER subnets_updated_at
  BEFORE UPDATE ON subnets FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- Clear legacy subnets.vlan_id when the backing VLAN row is deleted. The
-- trigger is attached to vlans (created above), but its function body
-- references subnets, so the function is declared here after the subnets
-- table exists. PL/pgSQL is late-bound so the function body is only
-- resolved at fire time — attaching the trigger before subnets existed
-- would be legal but this ordering keeps the read order obvious.
CREATE OR REPLACE FUNCTION vlans_cleanup_subnets_fn() RETURNS TRIGGER AS $$
BEGIN
    UPDATE subnets SET vlan_id = NULL WHERE vlan_fk = OLD.id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER vlans_before_delete_cleanup_subnets
  BEFORE DELETE ON vlans FOR EACH ROW EXECUTE FUNCTION vlans_cleanup_subnets_fn();

-- ---------------------------------------------------------------------------
-- contacts (v2.1.0, first-class contact objects)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL DEFAULT '',
  phone      TEXT NOT NULL DEFAULT '',
  org        TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_contacts_name  ON contacts(name);
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);

CREATE OR REPLACE TRIGGER contacts_updated_at
  BEFORE UPDATE ON contacts FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- devices + device_interfaces (v3.2.0, #394)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT COLLATE "C" NOT NULL UNIQUE,
  type       TEXT NOT NULL DEFAULT 'other',
  site_id    BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  vendor     TEXT NOT NULL DEFAULT '',
  model      TEXT NOT NULL DEFAULT '',
  serial     TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE OR REPLACE TRIGGER devices_updated_at
  BEFORE UPDATE ON devices FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

CREATE TABLE IF NOT EXISTS device_interfaces (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id   BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_device_interfaces_dev_name UNIQUE (device_id, name)
);

CREATE OR REPLACE TRIGGER device_interfaces_updated_at
  BEFORE UPDATE ON device_interfaces FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- addresses (individual IPs)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS addresses (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subnet_id        BIGINT NOT NULL REFERENCES subnets(id)  ON DELETE CASCADE,
  ip               TEXT COLLATE "C" NOT NULL,
  ip_bin           BYTEA NOT NULL,
  hostname         TEXT COLLATE "C" NOT NULL DEFAULT '',
  owner            TEXT NOT NULL DEFAULT '',
  note             TEXT NOT NULL DEFAULT '',
  grp              TEXT NOT NULL DEFAULT '',
  mac              TEXT NOT NULL DEFAULT '',
  expires_at       DATE NULL,
  status           TEXT NOT NULL DEFAULT 'used',
  owner_contact_id BIGINT NULL REFERENCES contacts(id) ON DELETE SET NULL,
  last_seen_at     TIMESTAMP NULL,
  is_stale         SMALLINT NOT NULL DEFAULT 0,
  device_id        BIGINT NULL REFERENCES devices(id)           ON DELETE SET NULL,
  interface_id     BIGINT NULL REFERENCES device_interfaces(id) ON DELETE SET NULL,
  custom_fields    TEXT NOT NULL DEFAULT '{}',                                  -- v3.5.0 #313/#595: JSON key/value per-entity metadata
  created_at       TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at       TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_addresses_subnet_ip UNIQUE (subnet_id, ip)
);

CREATE INDEX IF NOT EXISTS idx_addresses_subnet_ipbin     ON addresses(subnet_id, ip_bin);
CREATE INDEX IF NOT EXISTS idx_addresses_hostname         ON addresses(hostname);
CREATE INDEX IF NOT EXISTS idx_addresses_owner            ON addresses(owner);
CREATE INDEX IF NOT EXISTS idx_addresses_status           ON addresses(status);
CREATE INDEX IF NOT EXISTS idx_addresses_grp              ON addresses(grp);
CREATE INDEX IF NOT EXISTS idx_addresses_owner_contact_id ON addresses(owner_contact_id);
CREATE INDEX IF NOT EXISTS idx_addresses_is_stale         ON addresses(is_stale);
CREATE INDEX IF NOT EXISTS idx_addresses_device_id        ON addresses(device_id);
CREATE INDEX IF NOT EXISTS idx_addresses_interface_id     ON addresses(interface_id);

CREATE OR REPLACE TRIGGER addresses_updated_at
  BEFORE UPDATE ON addresses FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- address_history (per-address change log)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS address_history (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  address_id  BIGINT NULL,
  subnet_id   BIGINT NOT NULL,
  ip          TEXT NOT NULL,
  action      TEXT NOT NULL,
  user_id     BIGINT NULL,
  username    TEXT NULL,
  client_ip   TEXT NULL,
  user_agent  TEXT NULL,
  before_json TEXT NULL,
  after_json  TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_address_history_address_id ON address_history(address_id);
CREATE INDEX IF NOT EXISTS idx_address_history_subnet_id  ON address_history(subnet_id);

-- ---------------------------------------------------------------------------
-- audit_log (append-only, enforced by PL/pgSQL function + BEFORE triggers)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  user_id     BIGINT NULL,
  username    TEXT NULL,
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   BIGINT NULL,
  ip          TEXT NULL,
  user_agent  TEXT NULL,
  details     TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_action     ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log(created_at);

-- v2.11.0 #386: matches PgsqlDialect::append_only_trigger('audit_log').
-- Housekeeping routines (e.g. prune_audit_log) set
-- `SET LOCAL ipam.bypass_append_only = '1'` inside their transaction, do
-- the DELETE, and the GUC unsets on transaction end. Other connections
-- see NULL and continue to be blocked. SET LOCAL is per-transaction so
-- the bypass never leaks. current_setting(..., true) returns NULL for
-- unset GUCs instead of raising.
CREATE OR REPLACE FUNCTION audit_log_append_only_fn() RETURNS TRIGGER AS $$
BEGIN
    IF current_setting('ipam.bypass_append_only', true) IS DISTINCT FROM '1' THEN
        RAISE EXCEPTION 'audit_log is append-only';
    END IF;
    -- Bypass is active: allow the operation to proceed. Postgres BEFORE
    -- trigger functions suppress the row when they return NULL, so we must
    -- return OLD (for DELETE) or NEW (for UPDATE) to let the change through.
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER audit_log_no_update
  BEFORE UPDATE ON audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_append_only_fn();

CREATE OR REPLACE TRIGGER audit_log_no_delete
  BEFORE DELETE ON audit_log FOR EACH ROW EXECUTE FUNCTION audit_log_append_only_fn();

-- ---------------------------------------------------------------------------
-- login_attempts (rate limiter)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS login_attempts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip           TEXT NOT NULL,
  username     TEXT DEFAULT NULL,
  attempted_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_ip_time ON login_attempts(ip, attempted_at);
CREATE INDEX IF NOT EXISTS idx_login_attempts_username_time ON login_attempts(username, attempted_at);

-- ---------------------------------------------------------------------------
-- api_keys
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  key_hash     TEXT COLLATE "C" NOT NULL UNIQUE,
  created_at   TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  last_used_at TIMESTAMP NULL,
  is_active    SMALLINT NOT NULL DEFAULT 1,
  created_by   TEXT NOT NULL DEFAULT '',
  is_readonly  SMALLINT NOT NULL DEFAULT 0,
  description  TEXT NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------------------------
-- tags (v2.0.0)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tags (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT COLLATE "C" NOT NULL UNIQUE,
  colour     TEXT NOT NULL DEFAULT '#6c757d',
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE TABLE IF NOT EXISTS subnet_tags (
  subnet_id BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  tag_id    BIGINT NOT NULL REFERENCES tags(id)    ON DELETE CASCADE,
  PRIMARY KEY (subnet_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_subnet_tags_tag ON subnet_tags(tag_id);

CREATE TABLE IF NOT EXISTS address_tags (
  address_id BIGINT NOT NULL REFERENCES addresses(id) ON DELETE CASCADE,
  tag_id     BIGINT NOT NULL REFERENCES tags(id)      ON DELETE CASCADE,
  PRIMARY KEY (address_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_address_tags_tag ON address_tags(tag_id);

-- ---------------------------------------------------------------------------
-- site_contacts / subnet_contacts (multi-contact assignments, v3.0.0)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS site_contacts (
  site_id    BIGINT NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  role       TEXT   NOT NULL DEFAULT '',
  PRIMARY KEY (site_id, contact_id)
);

CREATE TABLE IF NOT EXISTS subnet_contacts (
  subnet_id  BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  role       TEXT   NOT NULL DEFAULT '',
  PRIMARY KEY (subnet_id, contact_id)
);

-- ---------------------------------------------------------------------------
-- alert_state (utilization alert tracker, v2.0.0)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_state (
  subnet_id       BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  level           TEXT NOT NULL,
  last_alerted_at TIMESTAMP NOT NULL,
  PRIMARY KEY (subnet_id, level),
  CONSTRAINT alert_state_level_check CHECK (level IN ('warn','crit'))
);

-- ---------------------------------------------------------------------------
-- utilization_snapshots (v3.1.0, sparkline history)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS utilization_snapshots (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subnet_id   BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  snapped_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  used_count  INTEGER NOT NULL,
  free_count  INTEGER NOT NULL,
  total_hosts INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_util_snap_subnet_time ON utilization_snapshots(subnet_id, snapped_at);

-- ---------------------------------------------------------------------------
-- aggregates (v2.4.0, RIR-assigned supernet tracking)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aggregates (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidr        TEXT COLLATE "C" NOT NULL UNIQUE,
  ip_version  SMALLINT NOT NULL,
  network     TEXT COLLATE "C" NOT NULL,
  network_bin BYTEA NOT NULL,
  prefix      SMALLINT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  rir         TEXT NOT NULL DEFAULT '',
  date_added  DATE NOT NULL DEFAULT CURRENT_DATE,
  notes       TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE OR REPLACE TRIGGER aggregates_updated_at
  BEFORE UPDATE ON aggregates FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- pd_pools + pd_delegations (v2.4.0, IPv6 Prefix Delegation)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pd_pools (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_subnet_id  BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  delegation_prefix SMALLINT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  site_id           BIGINT NULL REFERENCES sites(id) ON DELETE SET NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at        TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_pd_pools_parent_subnet UNIQUE (parent_subnet_id),
  CONSTRAINT pd_pools_prefix_range CHECK (delegation_prefix BETWEEN 1 AND 128)
);

CREATE OR REPLACE TRIGGER pd_pools_updated_at
  BEFORE UPDATE ON pd_pools FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

CREATE TABLE IF NOT EXISTS pd_delegations (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pool_id       BIGINT NOT NULL REFERENCES pd_pools(id) ON DELETE CASCADE,
  cidr          TEXT COLLATE "C" NOT NULL,
  subscriber_id BIGINT NULL REFERENCES contacts(id) ON DELETE SET NULL,
  delegated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  expires_at    TIMESTAMP NULL,
  notes         TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_pd_delegations_pool       ON pd_delegations(pool_id);
CREATE INDEX IF NOT EXISTS idx_pd_delegations_subscriber ON pd_delegations(subscriber_id);

-- ---------------------------------------------------------------------------
-- scan_schedules + scan_results (v2.3.0, network scanning)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scan_schedules (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subnet_id        BIGINT NOT NULL REFERENCES subnets(id) ON DELETE CASCADE,
  method           TEXT NOT NULL DEFAULT 'icmp',
  tcp_port         INTEGER NULL,
  interval_minutes INTEGER NOT NULL DEFAULT 60,
  is_active        SMALLINT NOT NULL DEFAULT 1,
  last_run_at      TIMESTAMP NULL,
  created_at       TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at       TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_scan_schedules_subnet UNIQUE (subnet_id),
  CONSTRAINT scan_schedules_method   CHECK (method IN ('icmp','tcp','both')),
  CONSTRAINT scan_schedules_tcp_port CHECK (tcp_port IS NULL OR (tcp_port BETWEEN 1 AND 65535)),
  CONSTRAINT scan_schedules_interval CHECK (interval_minutes >= 1)
);

CREATE OR REPLACE TRIGGER scan_schedules_updated_at
  BEFORE UPDATE ON scan_schedules FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

CREATE INDEX IF NOT EXISTS idx_scan_schedules_active ON scan_schedules(is_active, last_run_at);

CREATE TABLE IF NOT EXISTS scan_results (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subnet_id  BIGINT NOT NULL REFERENCES subnets(id)   ON DELETE CASCADE,
  address_id BIGINT NULL     REFERENCES addresses(id) ON DELETE SET NULL,
  ip         TEXT NOT NULL,
  method     TEXT NOT NULL,
  is_up      SMALLINT NOT NULL DEFAULT 0,
  latency_ms INTEGER NULL,
  scanned_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_scan_results_subnet_time ON scan_results(subnet_id, scanned_at);
CREATE INDEX IF NOT EXISTS idx_scan_results_address     ON scan_results(address_id, scanned_at);

-- ---------------------------------------------------------------------------
-- password_reset_tokens (v3.2.0, #541)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT COLLATE "C" NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at    TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_prt_user ON password_reset_tokens(user_id);

-- ---------------------------------------------------------------------------
-- webhooks + webhook_deliveries (v3.3.0, #337)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS webhooks (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  TEXT NOT NULL,
  url                   TEXT NOT NULL,
  secret                TEXT NOT NULL,
  events                TEXT NOT NULL DEFAULT '[]',
  is_active             SMALLINT NOT NULL DEFAULT 1,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_delivery_at      TIMESTAMPTZ,
  last_delivery_status  SMALLINT
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  webhook_id    BIGINT NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
  event_type    TEXT NOT NULL,
  payload       TEXT NOT NULL,
  signature     TEXT NOT NULL,
  attempt       SMALLINT NOT NULL DEFAULT 1,
  http_status   SMALLINT,
  response_body TEXT,
  error         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivered_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_wh_deliveries_wh ON webhook_deliveries(webhook_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_wh_deliveries_pending ON webhook_deliveries(delivered_at, attempt);

-- ---------------------------------------------------------------------------
-- schema_migrations (pre-seeded below with every historical version)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version    TEXT COLLATE "C" NOT NULL UNIQUE,
  applied_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

-- ---------------------------------------------------------------------------
-- totp_backup_codes (v3.6.0, #418)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS totp_backup_codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    code_hash   TEXT NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_totp_backup_codes_user ON totp_backup_codes(user_id);

-- ---------------------------------------------------------------------------
-- rate_limit_buckets (v3.6.0, #419)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rate_limit_buckets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_key   TEXT NOT NULL,
    window_start TEXT NOT NULL,
    count        INTEGER NOT NULL DEFAULT 0,
    UNIQUE (bucket_key, window_start)
);
-- idx_rate_limit_key_window is intentionally absent: UNIQUE (bucket_key, window_start) above
-- already provides the composite b-tree that the rate-limiter lookup uses.
CREATE INDEX IF NOT EXISTS idx_rate_limit_buckets_window_start ON rate_limit_buckets(window_start);

-- ---------------------------------------------------------------------------
-- webauthn_credentials (v3.15.0 #688: WebAuthn/Passkey credentials)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS webauthn_credentials (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id BYTEA   NOT NULL UNIQUE, -- PARAM_LOB required on all writes: see ipam_bind_binary()
  public_key    TEXT    NOT NULL,
  sign_count    INTEGER NOT NULL DEFAULT 0,
  name          VARCHAR(255) NOT NULL DEFAULT 'Passkey',
  created_at    TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  last_used_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_webauthn_credentials_user ON webauthn_credentials(user_id);

-- ---------------------------------------------------------------------------
-- settings (v2.6.0, key/value config registry)
-- "key" is quoted because it is a reserved word in some SQL dialects;
-- Postgres does not reserve it but quoting keeps the identifier exact.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS settings (
  tenant_id  INTEGER NULL,
  "key"      TEXT COLLATE "C" NOT NULL,
  value      TEXT NULL,
  type       TEXT NOT NULL DEFAULT 'string',
  updated_at TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT settings_type_check CHECK (type IN ('string','int','bool','json'))
);
-- Partial indexes enforce uniqueness correctly for NULL tenant_id (global rows).
-- PostgreSQL treats NULL as distinct in composite UNIQUE constraints, so a plain
-- UNIQUE(tenant_id, key) would allow multiple (NULL, 'theme') rows.
CREATE UNIQUE INDEX IF NOT EXISTS uq_settings_global ON settings ("key") WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_settings_tenant ON settings (tenant_id, "key") WHERE tenant_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- custom_field_defs (v3.5.0 #313/#595, admin-defined per-entity metadata)
-- "key" is quoted for consistency with settings.key; it is not reserved in
-- Postgres but the quoting makes the identifier exact and matches the
-- MySQL backtick treatment.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS custom_field_defs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT COLLATE "C" NOT NULL,
  "key"       TEXT COLLATE "C" NOT NULL,
  label       TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'text',
  options     TEXT NULL,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_required SMALLINT NOT NULL DEFAULT 0,
  is_deleted  SMALLINT NOT NULL DEFAULT 0,
  created_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at  TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_cfd_entity_key UNIQUE (entity_type, "key")
);

CREATE INDEX IF NOT EXISTS idx_cfd_entity_order ON custom_field_defs(entity_type, sort_order);

CREATE OR REPLACE TRIGGER custom_field_defs_updated_at
  BEFORE UPDATE ON custom_field_defs FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

-- ---------------------------------------------------------------------------
-- backup_destinations / backup_schedules / backup_runs (v3.17.0 #690 + v3.21.0 #799).
-- The legacy backup_history (v3.7.0 #423) and backup_log (v3.17.0 #690) tables
-- were collapsed into backup_runs in v3.21.0 (§A1 of backup_overhaul.md). The
-- 3.21.0-backup-runs migration creates backup_runs, copies surviving rows in,
-- and drops both legacy tables on upgrade.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS backup_destinations (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    TEXT      NOT NULL,
  type                    TEXT      NOT NULL,
  config                  TEXT      NOT NULL DEFAULT '{}',
  encrypt                 SMALLINT  NOT NULL DEFAULT 1,
  is_active               SMALLINT  NOT NULL DEFAULT 1,
  -- v3.25.0 #846 #848 #1076 #851: retention rehome + default flag + format/mode defaults.
  retention_hourly        SMALLINT  NOT NULL DEFAULT 0  CHECK (retention_hourly  >= 0),
  retention_daily         SMALLINT  NOT NULL DEFAULT 7  CHECK (retention_daily   >= 0),
  retention_weekly        SMALLINT  NOT NULL DEFAULT 4  CHECK (retention_weekly  >= 0),
  retention_monthly       SMALLINT  NOT NULL DEFAULT 3  CHECK (retention_monthly >= 0),
  is_default              SMALLINT  NOT NULL DEFAULT 0  CHECK (is_default IN (0,1)),
  default_backup_type     TEXT      NOT NULL DEFAULT 'logical'
                                    CHECK (default_backup_type IN ('database','logical')),
  default_encryption_mode TEXT      NOT NULL DEFAULT 'stored'
                                    CHECK (default_encryption_mode IN ('stored','transitory','unencrypted')),
  created_at              TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  updated_at              TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

CREATE OR REPLACE TRIGGER backup_destinations_updated_at
  BEFORE UPDATE ON backup_destinations FOR EACH ROW EXECUTE FUNCTION set_updated_at_utc();

CREATE TABLE IF NOT EXISTS backup_schedules (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_id    BIGINT    NOT NULL REFERENCES backup_destinations(id) ON DELETE CASCADE,
  frequency         TEXT      NOT NULL DEFAULT 'daily'
                              CHECK (frequency IN ('hourly','daily','weekly','monthly')),
  time_of_day       TEXT      NOT NULL DEFAULT '02:00',
  day_of_week       SMALLINT  NULL CHECK (day_of_week IS NULL OR day_of_week BETWEEN 0 AND 6),
  day_of_month      SMALLINT  NULL CHECK (day_of_month IS NULL OR day_of_month BETWEEN 1 AND 28),
  retention_hourly  SMALLINT  NOT NULL DEFAULT 0  CHECK (retention_hourly  >= 0),
  retention_daily   SMALLINT  NOT NULL DEFAULT 7  CHECK (retention_daily   >= 0),
  retention_weekly  SMALLINT  NOT NULL DEFAULT 4  CHECK (retention_weekly  >= 0),
  retention_monthly SMALLINT  NOT NULL DEFAULT 3  CHECK (retention_monthly >= 0),
  is_active         SMALLINT  NOT NULL DEFAULT 1  CHECK (is_active IN (0,1)),
  last_run_at       TIMESTAMP NULL,
  next_run_at       TIMESTAMP NULL,
  -- v3.23.0 #825 (F21): per-schedule notification overrides — see schema.sql.
  notify_override   SMALLINT  NOT NULL DEFAULT 0
                              CHECK (notify_override IN (0,1)),
  notify_on_failure SMALLINT  NULL CHECK (notify_on_failure IS NULL OR notify_on_failure IN (0,1)),
  notify_on_success SMALLINT  NULL CHECK (notify_on_success IS NULL OR notify_on_success IN (0,1)),
  notify_recipients TEXT      NULL,
  created_at        TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  CONSTRAINT uq_backup_schedules_destination UNIQUE (destination_id)
);
CREATE INDEX IF NOT EXISTS idx_backup_schedules_next_run ON backup_schedules(next_run_at);

-- v3.21.0 #799 (§A1): unified backup_runs replaces backup_history + backup_log.
-- Single enum `triggered_by` (schedule|manual|cli) drops the ambiguous
-- type+triggered_by combo from backup_log (#808 / F38). Single timestamp pair
-- (started_at + completed_at) closes B-P1-31 / #809.
CREATE TABLE IF NOT EXISTS backup_runs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_id  BIGINT    NULL REFERENCES backup_destinations(id) ON DELETE SET NULL,
  schedule_id     BIGINT    NULL REFERENCES backup_schedules(id)    ON DELETE SET NULL,
  backup_type     TEXT      NOT NULL DEFAULT 'database'
                            CHECK (backup_type IN ('database','logical')),
  encryption_mode TEXT      NOT NULL DEFAULT 'unencrypted'
                            CHECK (encryption_mode IN ('stored','transitory','unencrypted')),
  triggered_by    TEXT      NOT NULL DEFAULT 'manual'
                            CHECK (triggered_by IN ('schedule','manual','cli')),
  status          TEXT      NOT NULL DEFAULT 'running'
                            CHECK (status IN ('running','success','failed','retention_pruned')),
  filename        TEXT      NULL,
  size_bytes      BIGINT    NULL,
  checksum        TEXT      NULL,
  source_version  TEXT      NOT NULL DEFAULT '0.0.0',
  is_protected    SMALLINT  NOT NULL DEFAULT 0  CHECK (is_protected IN (0,1)),
  -- v3.25.0 #856: cancel-in-flight signal.
  cancel_requested SMALLINT NOT NULL DEFAULT 0  CHECK (cancel_requested IN (0,1)),
  error_message   TEXT      NULL,
  started_at      TIMESTAMP NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
  completed_at    TIMESTAMP NULL
);
CREATE INDEX IF NOT EXISTS idx_backup_runs_destination ON backup_runs(destination_id);
CREATE INDEX IF NOT EXISTS idx_backup_runs_schedule    ON backup_runs(schedule_id);
CREATE INDEX IF NOT EXISTS idx_backup_runs_started     ON backup_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_backup_runs_protected   ON backup_runs(is_protected) WHERE is_protected = 1;

-- ---------------------------------------------------------------------------
-- Pre-seed schema_migrations with every historical version so apply_migrations
-- is a no-op on fresh Postgres installs. New migrations added in v2.11.0+
-- must be idempotent and safe to run on Postgres, since they WILL execute
-- here. Matches schema.mysql.sql exactly so the three engines converge to
-- the same schema_migrations state (enforced by SchemaParityTest in #409).
--
-- Locked in #484 scope decision (2026-04-15): historical SQLite-only
-- migration closures are not refactored for multi-engine; this pre-seed is
-- how we keep them out of the Postgres execution path.
-- ---------------------------------------------------------------------------
INSERT INTO schema_migrations (version) VALUES
  ('0.3'),
  ('0.7'),
  ('0.9'),
  ('0.11'),
  ('0.12'),
  ('0.13'),
  ('0.14'),
  ('1.4'),
  ('1.9'),
  ('1.11'),
  ('1.12'),
  ('1.13'),
  ('1.19.0'),
  ('2.0.0-vlans'),
  ('2.0.0-site-hierarchy'),
  ('2.0.0-tags'),
  ('2.0.0-alert-state'),
  ('2.1.0-vrfs'),
  ('2.1.0-contacts'),
  ('2.3.0-scanning'),
  ('2.4.0-vrf-bgp'),
  ('2.4.0-vlan-ranges'),
  ('2.4.0-aggregates'),
  ('2.4.0-pd-pools'),
  ('2.6.0-settings'),
  ('2.8.0-subnet-notes'),
  ('2.8.0-alert-recipients'),
  ('2.9.0-blob-affinity'),
  ('2.12.0-account-lockout'),
  ('3.0.0-config-stub'),
  ('3.0.0-config-stub-rewrite'),
  ('3.0.0-site-contacts'),
  ('3.0.0-subnet-contacts'),
  ('3.1.0-user-timezone'),
  ('3.1.0-subnet-alerts-enabled'),
  ('3.1.0-utilization-snapshots'),
  ('3.2.0-devices'),
  ('3.2.0-password-reset'),
  ('3.3.0-webhooks'),
  ('3.4.0-dhcp-options'),
  ('3.5.0-custom-fields'),
  ('3.6.0-totp'),
  ('3.6.0-rate-limit'),
  ('3.6.0-lockout'),
  ('3.7.0-backup-history'),
  ('3.13.0-settings-cascade'),
  ('3.14.0-mfa-settings'),
  ('3.14.0-email-otp'),
  ('3.15.0-passkeys'),
  ('3.16.0-preferred-mfa-method'),
  ('3.17.0-backup'),
  ('3.21.0-backup-runs'),
  ('3.21.0-schedule-unique'),
  ('3.23.0-notify-overrides'),
  ('3.25.0-backup-destination-evolution')
ON CONFLICT (version) DO NOTHING;
