<?php
/**
 * v3.28.2 #1178 — Install Keys status panel (Settings page card).
 *
 * Shows the three install-root secrets, where each lives, and whether
 * it's set / auto-generated / missing. Surfaces the auto-generated state
 * that historically only existed in audit_log so operators see the event
 * even after dismissing the page_header() banner.
 *
 * Defensive: every state cell catches its own errors so a missing
 * audit_log row or a transient settings-table read does not crash the
 * Settings page.
 *
 * @var \PDO $db  provided by settings.php (which requires init.php)
 */
declare(strict_types=1);

/** @var array<string,mixed> $config */
$config = is_array($GLOBALS['config'] ?? null) ? $GLOBALS['config'] : [];

/**
 * Look up the most recent auto-gen audit timestamp for an install key.
 * Returns YYYY-MM-DD or null. Wrapped to swallow any PDO error so the
 * panel never crashes settings.php.
 */
$lookupAutoGenDate = static function (\PDO $db, string $action): ?string {
    try {
        $st = $db->prepare(
            'SELECT created_at FROM audit_log
              WHERE action = :a AND entity_type = :et
              ORDER BY created_at DESC LIMIT 1'
        );
        $st->execute([':a' => $action, ':et' => 'install_key']);
        $row = $st->fetch();
        if (is_array($row) && isset($row['created_at']) && is_string($row['created_at'])) {
            // created_at is "YYYY-MM-DD HH:MM:SS" on SQLite, ISO-ish on
            // MySQL / Postgres. Take the first 10 chars defensively.
            $d = substr($row['created_at'], 0, 10);
            return $d !== '' ? $d : null;
        }
    } catch (\Throwable $e) {
        error_log('[install_keys_panel] audit lookup ' . $action . ' failed: ' . $e->getMessage());
    }
    return null;
};

// app_secret state.
$appSecretCfg = is_string($config['app_secret'] ?? null) ? (string)$config['app_secret'] : '';
$appSecretAutoDate = $lookupAutoGenDate($db, 'app_secret_autogenerated');
if ($appSecretAutoDate !== null) {
    $appSecretState = '<span title="Auto-generated">&#9432;</span> auto-generated ' . e($appSecretAutoDate);
} elseif ($appSecretCfg !== '') {
    $appSecretState = '<span title="OK">&#10003;</span> set';
} else {
    $appSecretState = '<span title="Blank">&#9888;</span> blank';
}

// bootstrap_key state.
$bootstrapCfg = is_string($config['bootstrap_key'] ?? null) ? (string)$config['bootstrap_key'] : '';
$bootstrapValid = false;
if ($bootstrapCfg !== '') {
    try {
        $decoded = base64_decode($bootstrapCfg, true);
        $bootstrapValid = is_string($decoded) && strlen($decoded) === 32;
    } catch (\Throwable) {
        $bootstrapValid = false;
    }
}
$bootstrapAutoDate = $lookupAutoGenDate($db, 'bootstrap_key_autogenerated');
if ($bootstrapAutoDate !== null) {
    $bootstrapState = '<span title="Auto-generated">&#9432;</span> auto-generated ' . e($bootstrapAutoDate);
} elseif ($bootstrapValid) {
    $bootstrapState = '<span title="OK">&#10003;</span> set';
} elseif ($bootstrapCfg !== '') {
    $bootstrapState = '<span title="Malformed">&#9888;</span> malformed';
} else {
    $bootstrapState = '<span title="Blank">&#9888;</span> blank';
}

// backup_vault_key state — read via ipam_vault_status() which handles the
// wrapped envelope in the settings table.
$vaultState = '<span title="Unknown">&#9432;</span> unknown';
$vaultAction = '<a href="backup_admin_destinations.php">Admin &rarr; Backups &rarr; Destinations</a>';
try {
    $vaultStatus = ipam_vault_status();
    $state = $vaultStatus['state'];
    if ($state === 'present') {
        $vaultState = '<span title="OK">&#10003;</span> configured';
    } elseif ($state === 'unreadable') {
        $vaultState = '<span title="Unreadable">&#9888;</span> unreadable &mdash; encrypted scheduled backups disabled';
    } else {
        $vaultState = '<span title="Missing">&#9888;</span> missing &mdash; encrypted scheduled backups disabled';
    }
} catch (\Throwable $e) {
    error_log('[install_keys_panel] vault status failed: ' . $e->getMessage());
}
?>
<div class="card admin-notice" id="install-keys">
  <h2 style="margin-top:0;">Install keys</h2>
  <p class="muted">
    These three secrets protect your installation. Each lives in a different place;
    losing any one has different operational consequences. See
    <a href="https://github.com/seanmousseau/Simple-PHP-IPAM/blob/main/docs/backups.md#disaster-recovery">backups.md &rarr; Disaster recovery</a>.
  </p>
  <table class="install-keys" style="width:100%;border-collapse:collapse;">
    <thead>
      <tr>
        <th style="text-align:left;padding:0.25rem 0.5rem;">Secret</th>
        <th style="text-align:left;padding:0.25rem 0.5rem;">Source</th>
        <th style="text-align:left;padding:0.25rem 0.5rem;">State</th>
        <th style="text-align:left;padding:0.25rem 0.5rem;">Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding:0.25rem 0.5rem;"><code>app_secret</code></td>
        <td style="padding:0.25rem 0.5rem;"><code>config.php</code></td>
        <td style="padding:0.25rem 0.5rem;"><?= $appSecretState // nosemgrep ?></td>
        <td style="padding:0.25rem 0.5rem;">Back up <code>config.php</code></td>
      </tr>
      <tr>
        <td style="padding:0.25rem 0.5rem;"><code>bootstrap_key</code></td>
        <td style="padding:0.25rem 0.5rem;"><code>config.php</code></td>
        <td style="padding:0.25rem 0.5rem;"><?= $bootstrapState // nosemgrep ?></td>
        <td style="padding:0.25rem 0.5rem;">Back up <code>config.php</code></td>
      </tr>
      <tr>
        <td style="padding:0.25rem 0.5rem;"><code>backup_vault_key</code></td>
        <td style="padding:0.25rem 0.5rem;"><code>settings</code> table (wrapped)</td>
        <td style="padding:0.25rem 0.5rem;"><?= $vaultState // nosemgrep ?></td>
        <td style="padding:0.25rem 0.5rem;"><?= $vaultAction // nosemgrep ?></td>
      </tr>
    </tbody>
  </table>
</div>
