<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

require_once dirname(dirname(__DIR__)) . '/Simple-PHP-IPAM/dialects/Dialect.php';
require_once dirname(dirname(__DIR__)) . '/Simple-PHP-IPAM/dialects/DialectValidator.php';
require_once dirname(dirname(__DIR__)) . '/Simple-PHP-IPAM/dialects/PgsqlDialect.php';

/**
 * Unit tests for PgsqlDialect (#386).
 *
 * Pure string-output tests. These do NOT require a running Postgres server —
 * every assertion is against the exact SQL fragment PgsqlDialect emits,
 * which is deterministic and stateless. End-to-end DDL validation against
 * a real Postgres 14 service container is wired up by #388 (per-commit CI
 * job) and the containerized Playwright Postgres matrix slot.
 *
 * Structure mirrors MysqlDialectTest so that when a new interface method is
 * added, all three dialect test files get the parallel coverage.
 */
final class PgsqlDialectTest extends TestCase
{
    private PgsqlDialect $pgsql;

    protected function setUp(): void
    {
        $this->pgsql = new PgsqlDialect();
    }

    public function testDriverNameIsPgsql(): void
    {
        $this->assertSame('pgsql', $this->pgsql->driver_name());
    }

    public function testNowReturnsUtcTimestampExpression(): void
    {
        // (NOW() AT TIME ZONE 'utc') resolves to UTC regardless of session
        // timezone, matching SQLite's datetime('now') and MySQL's
        // UTC_TIMESTAMP(). Plain NOW() would drift across servers.
        $this->assertSame("(NOW() AT TIME ZONE 'utc')", $this->pgsql->now());
    }

    public function testAutoincrementIsBigintIdentity(): void
    {
        // GENERATED BY DEFAULT AS IDENTITY is the modern (PG10+) idiom
        // chosen over BIGSERIAL because IDENTITY columns don't leave orphan
        // sequences on table drop and integrate cleanly with pg_dump.
        $this->assertSame(
            'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
            $this->pgsql->autoincrement()
        );
    }

    public function testIndexedTextTypeIsPlainText(): void
    {
        // Postgres btree indexes on TEXT have no key length limit, so
        // $maxLen is ignored — matching SQLite's behaviour.
        $this->assertSame('TEXT', $this->pgsql->indexed_text_type());
        $this->assertSame('TEXT', $this->pgsql->indexed_text_type(191));
        $this->assertSame('TEXT', $this->pgsql->indexed_text_type(255));
    }

    public function testBinaryTypeIgnoresLength(): void
    {
        // BYTEA is variable-length; the $length argument is informational
        // only. ipam_bind_binary() uses PDO::PARAM_LOB so null bytes and
        // high bytes round-trip through pdo_pgsql without string-escaping.
        $this->assertSame('BYTEA', $this->pgsql->binary_type(16));
        $this->assertSame('BYTEA', $this->pgsql->binary_type(4));
        $this->assertSame('BYTEA', $this->pgsql->binary_type(255));
    }

    public function testCaseSensitiveCollationIsNull(): void
    {
        // Default Postgres collation (inherited from LC_COLLATE on initdb
        // with UTF-8 / C / en_US.UTF-8) is case-sensitive and byte-comparable
        // for ASCII. No COLLATE clause needed.
        $this->assertNull($this->pgsql->case_sensitive_collation());
    }

    public function testPragmaForeignKeysIsNullOnBoth(): void
    {
        // Postgres has no per-connection FK toggle equivalent to SQLite's
        // PRAGMA or MySQL's SET FOREIGN_KEY_CHECKS. Callers must check for
        // null and use deferred constraints or session_replication_role.
        $this->assertNull($this->pgsql->pragma_foreign_keys(true));
        $this->assertNull($this->pgsql->pragma_foreign_keys(false));
    }

    public function testUpsertSingleConflictColumn(): void
    {
        $sql = $this->pgsql->upsert('users', ['username'], ['email', 'updated_at']);
        $this->assertSame(
            'ON CONFLICT (username) DO UPDATE SET email = EXCLUDED.email, updated_at = EXCLUDED.updated_at',
            $sql
        );
    }

    public function testUpsertCompositeConflictColumns(): void
    {
        $sql = $this->pgsql->upsert('subnet_tags', ['subnet_id', 'tag_id'], ['created_at']);
        $this->assertSame(
            'ON CONFLICT (subnet_id, tag_id) DO UPDATE SET created_at = EXCLUDED.created_at',
            $sql
        );
    }

    public function testUpsertRequiresAtLeastOneConflictColumn(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->pgsql->upsert('users', [], ['email']);
    }

    public function testUpsertRequiresAtLeastOneUpdateColumn(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->pgsql->upsert('users', ['username'], []);
    }

    public function testUpsertOrIgnoreSingleConflictColumn(): void
    {
        // Direct native idiom on Postgres; shape matches SQLite exactly
        // except for the space after ON CONFLICT.
        $sql = $this->pgsql->upsert_or_ignore('settings', ['key']);
        $this->assertSame('ON CONFLICT (key) DO NOTHING', $sql);
    }

    public function testUpsertOrIgnoreCompositeConflictColumns(): void
    {
        $sql = $this->pgsql->upsert_or_ignore('subnet_tags', ['subnet_id', 'tag_id']);
        $this->assertSame('ON CONFLICT (subnet_id, tag_id) DO NOTHING', $sql);
    }

    public function testUpsertOrIgnoreRequiresAtLeastOneConflictColumn(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->pgsql->upsert_or_ignore('settings', []);
    }

    public function testAppendOnlyTriggerReturnsThreeStatements(): void
    {
        // Postgres needs one PL/pgSQL function plus two BEFORE triggers
        // (UPDATE, DELETE). The interface contract is `list<string>` so the
        // caller iterates and executes in order — matching the MySQL and
        // SQLite shapes which both return two statements.
        $stmts = $this->pgsql->append_only_trigger('audit_log');
        $this->assertCount(3, $stmts);
    }

    public function testAppendOnlyTriggerFunctionUsesPlpgsql(): void
    {
        $stmts = $this->pgsql->append_only_trigger('audit_log');
        // First statement is the function definition.
        $this->assertStringContainsString('CREATE OR REPLACE FUNCTION audit_log_append_only_fn()', $stmts[0]);
        $this->assertStringContainsString('LANGUAGE plpgsql', $stmts[0]);
        $this->assertStringContainsString("RAISE EXCEPTION 'audit_log is append-only'", $stmts[0]);
        $this->assertStringContainsString("ipam.bypass_append_only", $stmts[0]);
    }

    public function testAppendOnlyTriggerBypassReturnsOldOrNew(): void
    {
        // Regression guard for the #387 smoke-test finding: Postgres BEFORE
        // trigger functions suppress the row when they return NULL. The
        // bypass path MUST return OLD (for DELETE) or NEW (for UPDATE),
        // otherwise housekeeping DELETEs are silently dropped on the floor
        // without an error — the worst kind of broken.
        $stmts = $this->pgsql->append_only_trigger('audit_log');
        $this->assertStringContainsString("TG_OP = 'DELETE'", $stmts[0]);
        $this->assertStringContainsString('RETURN OLD', $stmts[0]);
        $this->assertStringContainsString('RETURN NEW', $stmts[0]);
    }

    public function testAppendOnlyTriggerStatementsCoverBothUpdateAndDelete(): void
    {
        $stmts = $this->pgsql->append_only_trigger('audit_log');
        $joined = implode("\n", $stmts);
        $this->assertStringContainsString('BEFORE UPDATE', $joined);
        $this->assertStringContainsString('BEFORE DELETE', $joined);
    }

    public function testAppendOnlyTriggerUsesCreateOrReplace(): void
    {
        // CREATE OR REPLACE TRIGGER (PG14+) is idempotent and is the primary
        // reason for the PG14 floor — no drop-and-recreate race window.
        $stmts = $this->pgsql->append_only_trigger('audit_log');
        $this->assertStringContainsString('CREATE OR REPLACE TRIGGER audit_log_no_update', $stmts[1]);
        $this->assertStringContainsString('CREATE OR REPLACE TRIGGER audit_log_no_delete', $stmts[2]);
    }

    public function testAppendOnlyTriggerEmbedsGivenTableName(): void
    {
        $stmts = $this->pgsql->append_only_trigger('some_other_table');
        foreach ($stmts as $stmt) {
            $this->assertStringContainsString('some_other_table', $stmt);
            $this->assertStringNotContainsString('audit_log', $stmt);
        }
    }

    public function testNullSafeEqUsesIsNotDistinctFrom(): void
    {
        // IS NOT DISTINCT FROM is the SQL-standard null-safe equality
        // operator; Postgres implements it natively. SQLite uses `IS :ph`
        // and MySQL uses `<=>` so the cross-engine helper must be used.
        $this->assertSame(
            'vrf_id IS NOT DISTINCT FROM :vrf',
            $this->pgsql->null_safe_eq('vrf_id', ':vrf')
        );
    }

    public function testIncrementOrInsertEmitsOnConflictDoUpdate(): void
    {
        // Postgres ON CONFLICT (cols) DO UPDATE with a table-qualified
        // counter increment to disambiguate from the EXCLUDED pseudo-table.
        $sql = $this->pgsql->increment_or_insert('rate_limit_buckets', ['bucket_key', 'window_start'], 'count');
        $this->assertSame(
            'INSERT INTO rate_limit_buckets (bucket_key, window_start, count) '
            . 'VALUES (:bucket_key, :window_start, 1) '
            . 'ON CONFLICT (bucket_key, window_start) DO UPDATE SET count = rate_limit_buckets.count + 1',
            $sql
        );
    }

    public function testIncrementOrInsertSingleKeyShape(): void
    {
        $sql = $this->pgsql->increment_or_insert('hits', ['path'], 'n');
        $this->assertSame(
            'INSERT INTO hits (path, n) VALUES (:path, 1) '
            . 'ON CONFLICT (path) DO UPDATE SET n = hits.n + 1',
            $sql
        );
    }

    public function testIncrementOrInsertRequiresAtLeastOneKeyColumn(): void
    {
        $this->expectException(InvalidArgumentException::class);
        $this->pgsql->increment_or_insert('hits', [], 'n');
    }
}
