name: Semgrep

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run custom security rules
        run: semgrep --config=.semgrep/rules.yml --error Simple-PHP-IPAM/
