/**
 * DHCP Config Export (v3.4.0) — export_dhcp.php endpoint, dhcp_pool.php export
 * card UI, and DHCP options round-trip via the subnet edit drawer.
 */
import { test, expect, type Browser, type BrowserContext, type Page } from '@playwright/test';
import {
  login, fetchPost, fetchGet, appUrl,
  ADMIN_USER, ADMIN_PASS,
  TEST_DHCP_CIDR,
  newAuthContext, subnetIdFor,
  RO_USER, RO_PASS, ensureRoUser,
} from '../fixtures/ipam';

let ctx: BrowserContext;
let page: Page;
let testSubnetId = 0;

// DHCP option values we'll set and verify round-trip
const DHCP_ROUTERS      = '10.55.0.1';
const DHCP_DNS          = '8.8.8.8,8.8.4.4';
const DHCP_DOMAIN       = 'test.local';
const DHCP_LEASE_DEF    = '43200';
const DHCP_LEASE_MAX    = '86400';
const DHCP_NEXT_SERVER  = '10.55.0.5';
const DHCP_BOOT_FILE    = 'pxelinux.0';

// Reserved address for export content assertions
const RESERVED_IP  = '10.55.0.50';
const RESERVED_MAC = 'DE:AD:BE:EF:00:01';
const RESERVED_HOST = 'pxe-client';

test.beforeAll(async ({ browser }: { browser: Browser }) => {
  ctx = await newAuthContext(browser);
  page = await ctx.newPage();
  await login(page, ADMIN_USER, ADMIN_PASS);
  await ensureRoUser(page);

  // Delete and recreate test subnet for a clean state
  await page.goto('subnets.php');
  const existingId = await subnetIdFor(page, TEST_DHCP_CIDR);
  if (existingId) {
    await fetchPost(page, appUrl('subnets.php'), {
      action: 'delete',
      id:     String(existingId),
    });
  }
  await fetchPost(page, appUrl('subnets.php'), {
    action:          'create',
    cidr:            TEST_DHCP_CIDR,
    description:     'dhcp export spec test subnet',
    confirm_overlap: '1',
  });
  await page.goto('subnets.php');
  testSubnetId = await subnetIdFor(page, TEST_DHCP_CIDR) ?? 0;

  // Add a reserved address with a MAC (needed for non-empty reservation sections)
  if (testSubnetId > 0) {
    await fetchPost(page, appUrl('addresses.php'), {
      action:    'create',
      subnet_id: String(testSubnetId),
      ip:        RESERVED_IP,
      hostname:  RESERVED_HOST,
      owner:     'pw-dhcp-export',
      status:    'reserved',
      mac:       RESERVED_MAC,
      note:      '',
      grp:       '',
    });

    // Set DHCP options so all tests can assert on them without order dependency
    await fetchPost(page, appUrl('subnets.php'), {
      action:             'update',
      id:                 String(testSubnetId),
      cidr:               TEST_DHCP_CIDR,
      description:        'dhcp export spec test subnet',
      dhcp_routers:       DHCP_ROUTERS,
      dhcp_dns_servers:   DHCP_DNS,
      dhcp_domain_name:   DHCP_DOMAIN,
      dhcp_lease_default: DHCP_LEASE_DEF,
      dhcp_lease_max:     DHCP_LEASE_MAX,
      dhcp_next_server:   DHCP_NEXT_SERVER,
      dhcp_boot_filename: DHCP_BOOT_FILE,
    });
  }
});

test.afterAll(async () => {
  if (testSubnetId > 0) {
    await page.goto('subnets.php');
    await fetchPost(page, appUrl('subnets.php'), {
      action: 'delete',
      id:     String(testSubnetId),
    });
  }
  await ctx?.close();
});

// ── export_dhcp.php — dhcpd format ────────────────────────────────────────────

test('export dhcpd: returns 200 text/plain', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=dhcpd'));
  expect(r.status).toBe(200);
  expect(r.contentType.toLowerCase()).toContain('text/plain');
});

test('export dhcpd: contains subnet block', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=dhcpd'));
  expect(r.body).toContain('subnet');
  expect(r.body).toContain('netmask');
});

test('export dhcpd: contains reserved address with hardware ethernet', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const r = await fetchGet(page, appUrl(`export_dhcp.php?format=dhcpd&subnets=${testSubnetId}`));
  expect(r.body).toContain('hardware ethernet');
  expect(r.body).toContain('fixed-address');
  expect(r.body).toContain(RESERVED_IP);
});

test('export dhcpd: contains header comment with version', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=dhcpd'));
  expect(r.body).toContain('# Generated by Simple PHP IPAM');
});

test('export dhcpd: subnet filter limits output', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const rAll    = await fetchGet(page, appUrl('export_dhcp.php?format=dhcpd'));
  const rFilter = await fetchGet(page, appUrl(`export_dhcp.php?format=dhcpd&subnets=${testSubnetId}`));
  // Filtered output cannot be longer than all-subnets output
  expect(rFilter.body.length).toBeLessThanOrEqual(rAll.body.length);
  // Filtered output still contains our test subnet
  expect(rFilter.body).toContain(TEST_DHCP_CIDR.split('/')[0]);
});

test('export dhcpd: preview mode returns 200 text/plain with content', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=dhcpd&preview=1'));
  expect(r.status).toBe(200);
  expect(r.contentType.toLowerCase()).toContain('text/plain');
  expect(r.body.length).toBeGreaterThan(0);
});

// ── export_dhcp.php — Kea JSON format ─────────────────────────────────────────

test('export kea: returns 200 application/json', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=kea'));
  expect(r.status).toBe(200);
  expect(r.contentType.toLowerCase()).toContain('application/json');
});

test('export kea: is valid JSON with Dhcp4.subnet4', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=kea'));
  let parsed: unknown;
  expect(() => { parsed = JSON.parse(r.body); }).not.toThrow();
  const obj = parsed as Record<string, unknown>;
  expect(obj).toHaveProperty('Dhcp4');
  const dhcp4 = obj['Dhcp4'] as Record<string, unknown>;
  expect(dhcp4).toHaveProperty('subnet4');
  expect(Array.isArray(dhcp4['subnet4'])).toBe(true);
});

test('export kea: subnet4 entry contains test subnet CIDR', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const r = await fetchGet(page, appUrl(`export_dhcp.php?format=kea&subnets=${testSubnetId}`));
  const obj = JSON.parse(r.body) as { Dhcp4: { subnet4: Array<{ subnet: string }> } };
  const subnets = obj.Dhcp4.subnet4;
  expect(subnets.length).toBeGreaterThan(0);
  const found = subnets.some(s => s.subnet === TEST_DHCP_CIDR);
  expect(found).toBe(true);
});

test('export kea: reservations array contains reserved MAC', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const r = await fetchGet(page, appUrl(`export_dhcp.php?format=kea&subnets=${testSubnetId}`));
  type KeaSubnet = { subnet: string; reservations: Array<{ 'hw-address': string; 'ip-address': string }> };
  const obj = JSON.parse(r.body) as { Dhcp4: { subnet4: KeaSubnet[] } };
  const entry = obj.Dhcp4.subnet4.find(s => s.subnet === TEST_DHCP_CIDR);
  expect(entry).toBeDefined();
  const reservations = entry!.reservations ?? [];
  expect(reservations.length).toBeGreaterThan(0);
  const found = reservations.some(res => res['ip-address'] === RESERVED_IP);
  expect(found).toBe(true);
});

test('export kea: preview mode returns 200 with JSON content', async () => {
  const r = await fetchGet(page, appUrl('export_dhcp.php?format=kea&preview=1'));
  expect(r.status).toBe(200);
  expect(r.body.length).toBeGreaterThan(0);
  expect(() => JSON.parse(r.body)).not.toThrow();
});

// ── DHCP options round-trip via subnet edit drawer ─────────────────────────────

test('subnet edit: DHCP options section exists in edit drawer', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  await page.goto('subnets.php');
  const editBtn = page.locator(`.subnet-edit-btn[data-id="${testSubnetId}"]`);
  await expect(editBtn).toBeVisible();
  await editBtn.click();
  const drawer = page.locator('#subnet-edit-drawer');
  await expect(drawer).toBeVisible();
  await expect(drawer.locator('.dhcp-options-group')).toBeVisible();
});

test('subnet edit: DHCP options can be saved and round-trip', async () => {
  expect(testSubnetId).toBeGreaterThan(0);

  // DHCP options were set in beforeAll — open drawer and verify round-trip
  await page.goto('subnets.php');
  const editBtn = page.locator(`.subnet-edit-btn[data-id="${testSubnetId}"]`);
  await editBtn.click();
  const drawer = page.locator('#subnet-edit-drawer');
  await expect(drawer).toBeVisible();

  await expect(drawer.locator('#subnet-edit-dhcp-routers')).toHaveValue(DHCP_ROUTERS);
  await expect(drawer.locator('#subnet-edit-dhcp-dns-servers')).toHaveValue(DHCP_DNS);
  await expect(drawer.locator('#subnet-edit-dhcp-domain-name')).toHaveValue(DHCP_DOMAIN);
  await expect(drawer.locator('#subnet-edit-dhcp-lease-default')).toHaveValue(DHCP_LEASE_DEF);
  await expect(drawer.locator('#subnet-edit-dhcp-lease-max')).toHaveValue(DHCP_LEASE_MAX);
  await expect(drawer.locator('#subnet-edit-dhcp-next-server')).toHaveValue(DHCP_NEXT_SERVER);
  await expect(drawer.locator('#subnet-edit-dhcp-boot-filename')).toHaveValue(DHCP_BOOT_FILE);
});

test('subnet edit: DHCP options details auto-opens when values are set', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  await page.goto('subnets.php');
  const editBtn = page.locator(`.subnet-edit-btn[data-id="${testSubnetId}"]`);
  await editBtn.click();
  const details = page.locator('.dhcp-options-group');
  // details[open] attribute should be present when any DHCP field is set
  await expect(details).toHaveAttribute('open');
});

test('export dhcpd: DHCP options appear in subnet block after saving', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const r = await fetchGet(page, appUrl(`export_dhcp.php?format=dhcpd&subnets=${testSubnetId}`));
  expect(r.body).toContain(`option routers ${DHCP_ROUTERS}`);
  expect(r.body).toContain(`option domain-name-servers ${DHCP_DNS}`);
  expect(r.body).toContain(`option domain-name "${DHCP_DOMAIN}"`);
  expect(r.body).toContain(`default-lease-time ${DHCP_LEASE_DEF}`);
  expect(r.body).toContain(`max-lease-time ${DHCP_LEASE_MAX}`);
  expect(r.body).toContain(`next-server ${DHCP_NEXT_SERVER}`);
  expect(r.body).toContain(`filename "${DHCP_BOOT_FILE}"`);
});

test('export kea: option-data populated after saving DHCP options', async () => {
  expect(testSubnetId).toBeGreaterThan(0);
  const r = await fetchGet(page, appUrl(`export_dhcp.php?format=kea&subnets=${testSubnetId}`));
  type KeaSubnetOpts = { subnet: string; 'option-data': Array<{ name: string }> };
  const obj = JSON.parse(r.body) as { Dhcp4: { subnet4: KeaSubnetOpts[] } };
  const entry = obj.Dhcp4.subnet4.find(s => s.subnet === TEST_DHCP_CIDR);
  expect(entry).toBeDefined();
  const opts = (entry!['option-data'] ?? []).map(o => o.name);
  expect(opts).toContain('routers');
  expect(opts).toContain('domain-name-servers');
  expect(opts).toContain('domain-name');
});

// ── dhcp_pool.php — export UI card ────────────────────────────────────────────

test('dhcp_pool page: export card is present', async () => {
  await page.goto('dhcp_pool.php');
  const exportCard = page.locator('.card').filter({
    has: page.locator('h2', { hasText: /Export DHCP Config/i }),
  });
  await expect(exportCard).toBeVisible();
});

test('dhcp_pool page: download dhcpd.conf button present', async () => {
  await page.goto('dhcp_pool.php');
  const btn = page.locator('button', { hasText: /dhcpd\.conf/i });
  await expect(btn).toBeVisible();
});

test('dhcp_pool page: download Kea JSON button present', async () => {
  await page.goto('dhcp_pool.php');
  const btn = page.locator('button', { hasText: /Kea JSON/i });
  await expect(btn).toBeVisible();
});

test('dhcp_pool page: preview button toggles textarea visible', async () => {
  await page.goto('dhcp_pool.php');
  const previewBtn = page.locator('#dhcp-preview-btn');
  await expect(previewBtn).toBeVisible();

  const previewOutput = page.locator('#dhcp-preview-output');
  await expect(previewOutput).toBeHidden();

  await previewBtn.click();

  await expect(previewOutput).toBeVisible({ timeout: 5000 });
  // Wait for fetch to complete — textarea leaves the "Loading…" placeholder
  await expect(previewOutput).not.toHaveValue('Loading\u2026', { timeout: 10000 });
  await expect(previewOutput).not.toHaveValue('', { timeout: 1000 });
  const content = await previewOutput.inputValue();
  expect(content.length).toBeGreaterThan(0);
  expect(content).toContain('subnet');
});

// ── Access control ─────────────────────────────────────────────────────────────

test('export dhcpd: readonly user is denied (403)', async () => {
  const roCtx = await newAuthContext(ctx.browser()!);
  const roPage = await roCtx.newPage();
  try {
    await login(roPage, RO_USER, RO_PASS);
    const r = await fetchGet(roPage, appUrl('export_dhcp.php?format=dhcpd'));
    expect(r.status).toBe(403);
  } finally {
    await roCtx.close();
  }
});

test('export kea: readonly user is denied (403)', async () => {
  const roCtx = await newAuthContext(ctx.browser()!);
  const roPage = await roCtx.newPage();
  try {
    await login(roPage, RO_USER, RO_PASS);
    const r = await fetchGet(roPage, appUrl('export_dhcp.php?format=kea'));
    expect(r.status).toBe(403);
  } finally {
    await roCtx.close();
  }
});
